Dot env configuration
bixlabs/go-layout pull request #5
Opened 2019-02-04 02:29 UTC by jac1013

#4

2019-02-07 22:48 UTC, rkmax commented on .env-template
> +WEB_SERVER_PORT=9000
Is kinda silly but it's best on the template set the same value as the default, 3000

2019-02-08 10:38 UTC, jac1013 commented on .env-template
> +WEB_SERVER_PORT=9000
My intention is to show that when people uses this as the `.env` file they will see the application running in a different port (which is feedback that the configuration is working), what do you think?

2019-02-12 17:23 UTC, DiegoSabalsa commented on api/todo.go
>  	// By default it serves on :8080 unless a
By default it serves on 3000

2019-02-12 17:24 UTC, DiegoSabalsa commented on api/todo.go
>  	// By default it serves on :8080 unless a
By default it serves in 3000

2019-02-12 18:10 UTC, DiegoSabalsa requested changes

2019-02-12 18:10 UTC, DiegoSabalsa commented on api/todo.go
>  	// By default it serves on :8080 unless a
```suggestion
	// By default it serves on envDefalut unless a
```

2019-02-12 18:26 UTC, DiegoSabalsa approved these changes

2019-02-12 18:26 UTC, merged